[workspace]
resolver = "2"
members = [
    "crates/mbbs",
    "crates/mbbs16",
    "crates/mbbs32",
    "crates/mbbs-server",
    "crates/mud-core",
    "crates/mud-server",
    "crates/mud-oracle",
    "crates/mud-client",
]

[workspace.package]
edition = "2024"
license = "MIT"
publish = false

[workspace.lints.clippy]
all = "warn"
