[workspace]
resolver = "2"
members = [
    "crates/mbbs",
    "crates/mbbs-lua",
    "crates/mbbs-machine",
    "crates/btrieve",
    "crates/btrieve-oracle",
    "crates/mbbs-server",
    "crates/dos",
    "crates/dos-runtime",
    "crates/textscreen",
    "crates/cnf",
    "crates/bropey",
]

[workspace.package]
edition = "2024"
license = "MIT"
publish = false

[workspace.lints.clippy]
all = "warn"
