[package]
name = "mbbs"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
btrieve = { path = "../btrieve" }
libc = "0.2"
mbbs-machine = { path = "../mbbs-machine" }

[dev-dependencies]
btrieve-engine = { path = "../btrieve-engine" }

[lints]
workspace = true
