//! CP437 is one table with two readings. These tests pin both, and pin that
//! they differ in exactly one place.

use textscreen::cp437::{decode_screen, decode_wire, encode, TABLE};

#[test]
fn ascii_is_itself_in_both_readings() {
    for b in 0x20u8..0x7f {
        let s = String::from(b as char);
        assert_eq!(decode_wire(&[b]), s, "wire, byte {b:#04x}");
        assert_eq!(decode_screen(&[b]), s, "screen, byte {b:#04x}");
    }
}

#[test]
fn the_two_readings_differ_on_control_bytes() {
    // On the wire a C0 byte is a control code and must pass through: the ANSI
    // escapes, the line endings, the anti-bot backspaces all live here.
    assert_eq!(decode_wire(&[0x11]), "\u{11}");
    assert_eq!(decode_wire(&[0x1b]), "\u{1b}");
    // On a text screen the same byte is a glyph. 0x11 is a left-pointing
    // triangle, which is what a DOS menu draws its arrows with.
    assert_eq!(decode_screen(&[0x11]), "\u{25c4}");
    // 0x7f is the other place they differ: CP437 maps it to a house glyph,
    // but the wire reading is the identity below 0x80.
    assert_eq!(decode_wire(&[0x7f]), "\u{7f}");
    assert_eq!(decode_screen(&[0x7f]), "\u{2302}");
}

#[test]
fn the_two_functions_share_one_table() {
    // This proves only that `decode_wire`'s and `decode_screen`'s high-half
    // branches read the same `TABLE[b as usize]` expression -- i.e. that the
    // two functions have not diverged in code (say, someone later points one
    // of them at a second, private table). For any fixed `b >= 0x80` both
    // sides evaluate the identical expression, so this test passes no matter
    // what characters `TABLE` actually holds -- it does NOT validate the
    // table's contents. That validation is `table_matches_the_independent_reference`,
    // below, which checks each entry against a fixture built from an
    // authority outside this crate.
    for b in 0x80u8..=0xff {
        assert_eq!(
            decode_wire(&[b]),
            decode_screen(&[b]),
            "byte {b:#04x} disagrees between the two readings"
        );
    }
}

#[test]
fn the_high_half_is_box_drawing_and_accents() {
    assert_eq!(decode_wire(&[0xc9, 0xcd, 0xbb]), "\u{2554}\u{2550}\u{2557}");
    assert_eq!(decode_wire(&[0x82]), "\u{e9}");
}

#[test]
fn every_byte_survives_a_wire_round_trip() {
    let all: Vec<u8> = (0u8..=0xff).collect();
    assert_eq!(encode(&decode_wire(&all)), all);
}

#[test]
fn unmappable_characters_become_question_marks() {
    assert_eq!(encode("\u{4e2d}"), b"?".to_vec());
}

#[test]
fn encode_can_synthesize_the_telnet_iac_byte() {
    // CP437 0xFF is a non-breaking space -- and 0xFF is also telnet IAC. A
    // caller on a telnet path must double it. Pinned here so the hazard lives
    // with the function instead of in one caller's comment.
    assert_eq!(encode("\u{a0}"), vec![0xff]);
}

/// `cp437-reference.txt`: exactly 256 characters in byte order (byte 0x00
/// first), followed by one trailing newline. Generated by:
///
/// ```sh
/// python3 -c "import sys; sys.stdout.write(bytes(range(0x20,0x7f)).decode('cp437'))"  # bytes 0x20..=0x7E
/// python3 -c "import sys; sys.stdout.write(bytes(range(0x80,0x100)).decode('cp437'))" # bytes 0x80..=0xFF
/// ```
///
/// 223 of the 256 entries (0x20..=0x7E and 0x80..=0xFF) therefore come from
/// Python's stdlib `cp437` codec -- an authority independent of this crate's
/// own `TABLE`. The other 33 (0x00..=0x1F and 0x7F) cannot come from Python,
/// and cannot come from any character-encoding mapping at all: Unicode
/// vendor mappings for CP437 (e.g. `CP437.TXT`) deliberately encode that
/// range as identity C0/DEL control characters, the same thing Python's
/// codec does, because they describe *encoding*, not *display*. The glyphs
/// `TABLE` and this fixture use there -- the smiley, the arrows, the house
/// -- are a separate thing: the IBM PC ROM character generator's on-screen
/// rendering of those bytes, a hardware display convention with no
/// character-encoding authority to cite. 32 of those 33 are hand-transcribed
/// instead, from the Code page 437 control-picture glyph table as commonly
/// tabulated (e.g. the "Control codes" column of the Code page 437
/// reference table) -- independent of `TABLE`'s own source, but still a
/// manual transcription, so they carry the same transcription risk the
/// original table did.
///
/// Entry 0x00 is the one exception even to that: it is pinned here as `' '`,
/// not the control-picture table's NUL glyph, matching `TABLE`'s own
/// deliberate departure (a cleared cell should paint as a blank, not as
/// visible noise). There is no independent authority for this entry at
/// all -- the "authority outside this crate" framing below does not cover
/// it, and this fixture agreeing with `TABLE` here only proves the two were
/// edited together, not that either is right.
///
/// All 256 entries are, as of this fixture, protected against a *future*
/// accidental edit to `TABLE`; the 33 hand-pinned ones are not protected
/// against a transcription error shared by both this fixture and `TABLE`
/// on day one, and entry 0x00 additionally has no external check at all.
const REFERENCE: &str = include_str!("cp437-reference.txt");

#[test]
fn table_matches_the_independent_reference() {
    let reference: Vec<char> = REFERENCE.trim_end_matches('\n').chars().collect();
    assert_eq!(
        reference.len(),
        256,
        "cp437-reference.txt must hold exactly 256 characters"
    );
    for b in 0u16..=0xff {
        let b = b as u8;
        let want = reference[b as usize];
        let got = TABLE[b as usize];
        assert_eq!(
            got, want,
            "TABLE[{b:#04x}] is {got:?}, cp437-reference.txt says {want:?}"
        );
    }
}
